//! The Agent runtime: a cancellable, multi-turn inference-then-tool loop.

use std::{
    collections::{BTreeSet, HashMap, VecDeque},
    fmt::Write as _,
    path::{Path, PathBuf},
    sync::Arc,
};

use gocode_core::{
    CancellationToken, ChatMessage, ChatStreamEvent, FinishReason, ModelId, PersonalityName,
    Provider, ProviderToolCall,
};
use gocode_tools::{
    FileChangeObserver, FileSnapshot, ToolCall, ToolContext, ToolError, ToolEvent, ToolEventSink,
    ToolRegistry, ToolResult, ToolStatus, permissions::PermissionContext,
};
use tokio::sync::mpsc;

use crate::{
    context::{RequestContext, build_request},
    error::AgentError,
    events::{AgentCompletion, AgentEvent, AgentRunStats, AgentWarning, TerminationReason},
    ids::AgentRunId,
    limits::{AgentLimit, AgentLimits},
    progress::TaskProgress,
    state::AgentState,
    toolcalls::ToolCallAssembler,
};

/// Sent as one final no-tools user turn when a safety limit is reached, asking the model to
/// land the run gracefully instead of ending it silently mid-work.
const SOFT_LANDING_PROMPT: &str = "You've reached this run's safety budget and must stop now. \
    Do not request any more tools. Reply with a concise plain-text summary covering: changes \
    made, validations performed, the current state, and any blockers or remaining steps.";

const VALIDATION_PENDING_PROMPT: &str = "You changed project files but did not validate them. \
    Do not request any more tools and do not claim the task is complete. Reply with a concise \
    plain-text summary covering: changes made, validations performed, the current state, and \
    the exact validation still required.";

const RECOVERY_EVIDENCE_REQUIRED: &str = "The last validation failed. Before another edit, inspect \
    the failure with read_file, search, list_files, or diagnostics and use that new evidence to \
    choose a different fix.";

/// Number of most recent tool calls kept for [`local_budget_summary`]'s fallback report.
const RECENT_TOOL_LOG_CAPACITY: usize = 5;

/// Assembles a minimal local summary when a safety limit is reached and the model's own
/// wrap-up inference also fails, so the run still ends with something actionable instead of
/// nothing at all.
fn local_budget_summary(
    limit: AgentLimit,
    changed_files: &BTreeSet<PathBuf>,
    recent_tool_log: &VecDeque<String>,
) -> String {
    let mut summary = format!(
        "Run stopped: {limit}. The model could not produce a summary, so here is what's known from the run:\n"
    );

    if changed_files.is_empty() {
        summary.push_str("- No files were changed.\n");
    } else {
        summary.push_str("- Files changed:\n");
        for path in changed_files {
            let _ = writeln!(summary, "  - {}", path.display());
        }
    }

    if recent_tool_log.is_empty() {
        summary.push_str("- No tools were executed.\n");
    } else {
        summary.push_str("- Last tool calls:\n");
        for entry in recent_tool_log {
            let _ = writeln!(summary, "  - {entry}");
        }
    }

    summary
}

/// Everything one agent run needs beyond the [`Agent`]'s own configuration.
pub struct AgentRequest {
    /// The user's message that starts this run.
    pub prompt: String,
    /// The model to use for every turn of this run.
    pub model: ModelId,
    /// Root directory that bounds every tool's filesystem and process access.
    pub project_root: PathBuf,
    /// Parsed `.gocode/instructions.md` content, if any.
    pub instructions: Option<String>,
    /// Parsed `AGENTS.md` content from the project root, if any, generated by `/init` or written
    /// by hand.
    pub project_overview: Option<String>,
    /// Formatted summary of discovered skills (global and project), if any, listing each one's
    /// name, description, and file path for the model to read on demand.
    pub skills_summary: Option<String>,
    /// Whether the selected model's capabilities allow tool definitions to be sent.
    ///
    /// The Agent does not resolve model capabilities itself; the caller gates this using
    /// `gocode_core::ModelCapabilities` before starting the run (`docs/AGENT.md` §109).
    pub tools_enabled: bool,
    /// User-selected reasoning-effort level, forwarded to the provider request as-is.
    pub reasoning_effort: Option<String>,
    /// Presentation style only; it cannot alter tool access or permission policy.
    pub personality: PersonalityName,
    /// Prior conversation turns to seed this run's history with, oldest first. Empty for a fresh
    /// conversation.
    pub history: Vec<ChatMessage>,
}

/// Long-lived collaborators an [`Agent`] uses to drive every run.
pub struct Agent {
    provider: Arc<dyn Provider>,
    tools: Arc<ToolRegistry>,
    permissions: PermissionContext,
    limits: AgentLimits,
    file_change_observer: Option<Arc<dyn FileChangeObserver>>,
}

impl Agent {
    /// Creates an agent from its provider, tool registry, permission policy, and limits.
    #[must_use]
    pub fn new(
        provider: Arc<dyn Provider>,
        tools: Arc<ToolRegistry>,
        permissions: PermissionContext,
        limits: AgentLimits,
    ) -> Self {
        Self {
            provider,
            tools,
            permissions,
            limits,
            file_change_observer: None,
        }
    }

    /// Attaches an observer notified after every tool call that writes a file (e.g. an LSP
    /// client keeping open documents in sync). Optional: a run works identically without one.
    #[must_use]
    pub fn with_file_change_observer(mut self, observer: Arc<dyn FileChangeObserver>) -> Self {
        self.file_change_observer = Some(observer);
        self
    }

    /// Drives one complete agent run to completion, cancellation, or failure.
    ///
    /// Emits [`AgentEvent`]s on `events` throughout; the caller decides how (or whether) to
    /// render them. Only one run should be active per [`Agent`] instance at a time
    /// (`docs/AGENT.md` §106); nothing here prevents concurrent calls, but the MVP contract
    /// assumes the caller serializes them.
    ///
    /// # Errors
    ///
    /// Returns [`AgentError`] when the provider fails, a configured limit stops the run, or the
    /// run is cancelled. Recoverable tool failures do not appear here; they are returned to the
    /// model as tool results and the run continues.
    pub async fn run(
        &self,
        request: AgentRequest,
        events: mpsc::Sender<AgentEvent>,
        cancellation: CancellationToken,
    ) -> Result<AgentCompletion, AgentError> {
        let run_id = AgentRunId::new();
        let _ = events.send(AgentEvent::Started).await;

        let outcome = self.drive(run_id, request, &events, cancellation).await;

        match &outcome {
            Ok(completion) => {
                let _ = events.send(AgentEvent::Completed(completion.clone())).await;
            }
            Err(AgentError::Cancelled) => {
                let _ = events.send(AgentEvent::Cancelled).await;
            }
            Err(_) => {}
        }

        outcome
    }

    #[allow(
        clippy::too_many_lines,
        reason = "the inference-then-tool driving loop is intentionally kept in one place"
    )]
    async fn drive(
        &self,
        run_id: AgentRunId,
        request: AgentRequest,
        events: &mpsc::Sender<AgentEvent>,
        cancellation: CancellationToken,
    ) -> Result<AgentCompletion, AgentError> {
        let tool_cancellation = tokio_util::sync::CancellationToken::new();
        let _bridge_guard = bridge_cancellation(cancellation.clone(), tool_cancellation.clone());

        let mut stats = AgentRunStats::default();
        let mut history = request.history.clone();
        history.push(ChatMessage::User(request.prompt.clone()));
        let tool_defs = if request.tools_enabled {
            map_tool_definitions(&self.tools)
        } else {
            Vec::new()
        };

        let mut consecutive_failures = 0usize;
        let mut last_call_signature: Option<(String, String, String)> = None;
        let mut same_call_repeat_count = 0usize;
        let mut changed_files: BTreeSet<PathBuf> = BTreeSet::new();
        let mut recent_tool_log: VecDeque<String> = VecDeque::new();
        let mut progress = TaskProgress::default();

        let mut normal_final_text: Option<String> = None;
        let mut budget_exhausted: Option<AgentLimit> = None;

        'drive: loop {
            if cancellation.is_cancelled() {
                return Err(AgentError::Cancelled);
            }
            if stats.turns >= self.limits.max_turns {
                budget_exhausted = Some(AgentLimit::MaxTurns);
                break 'drive;
            }
            stats.turns += 1;
            let _ = events
                .send(AgentEvent::StateChanged(AgentState::Inference))
                .await;

            let (text, tool_calls, input_tokens) = self
                .run_turn(&request, &history, &tool_defs, events, &cancellation)
                .await?;
            if input_tokens.is_some() {
                stats.last_input_tokens = input_tokens;
            }

            history.push(ChatMessage::Assistant {
                text: text.clone(),
                tool_calls: tool_calls.iter().map(to_provider_tool_call).collect(),
            });

            if tool_calls.is_empty() {
                if progress.requires_validation() {
                    budget_exhausted = Some(AgentLimit::ValidationPending);
                    break 'drive;
                }
                normal_final_text = Some(text.unwrap_or_default());
                break 'drive;
            }

            if stats.tool_calls + tool_calls.len() > self.limits.max_total_tool_calls {
                budget_exhausted = Some(AgentLimit::MaxTotalToolCalls);
                break 'drive;
            }
            if tool_calls.len() > self.limits.max_tool_calls_per_turn {
                return Err(AgentError::LimitReached(AgentLimit::MaxToolCallsPerTurn));
            }

            let _ = events
                .send(AgentEvent::StateChanged(AgentState::ExecutingTools))
                .await;

            for call in tool_calls {
                if cancellation.is_cancelled() {
                    return Err(AgentError::Cancelled);
                }
                stats.tool_calls += 1;
                let _ = events.send(AgentEvent::ToolRequested(call.clone())).await;

                let before_snapshots = capture_before_snapshots(&request.project_root, &call);

                let tool_result = if progress.blocks_edit(&call) {
                    ToolResult::failed(call.id.clone(), RECOVERY_EVIDENCE_REQUIRED)
                } else {
                    self.execute_tool(&request, &call, &tool_cancellation, events)
                        .await?
                };
                progress.observe(&call, &tool_result);

                // A loop needs both the same request and unchanged evidence. Polling a source
                // with the same arguments can be a valid investigation when the result changes.
                let signature = (
                    call.name.as_str().to_string(),
                    call.arguments.to_string(),
                    tool_evidence_signature(&tool_result),
                );
                if last_call_signature.as_ref() == Some(&signature) {
                    same_call_repeat_count += 1;
                } else {
                    last_call_signature = Some(signature);
                    same_call_repeat_count = 1;
                }

                let status_label = match tool_result.status {
                    ToolStatus::Success => "ok",
                    ToolStatus::Failed => "failed",
                    ToolStatus::Cancelled => "cancelled",
                    ToolStatus::Denied => "denied",
                };
                recent_tool_log.push_back(format!("{} -> {status_label}", call.name.as_str()));
                if recent_tool_log.len() > RECENT_TOOL_LOG_CAPACITY {
                    recent_tool_log.pop_front();
                }

                if tool_result.status == ToolStatus::Success {
                    consecutive_failures = 0;
                } else {
                    stats.failed_tool_calls += 1;
                    consecutive_failures += 1;
                }

                for change in &tool_result.metadata.affected_files {
                    changed_files.insert(change.path.clone());
                    let _ = events.send(AgentEvent::FileChanged(change.clone())).await;

                    if let Some(observer) = &self.file_change_observer {
                        observer.notify(&request.project_root, change);
                    }

                    let after = read_workspace_file(&request.project_root, &change.path);
                    let before = before_snapshots.get(&change.path).cloned().flatten();
                    let _ = events
                        .send(AgentEvent::FileSnapshot(FileSnapshot {
                            path: change.path.clone(),
                            before,
                            after,
                        }))
                        .await;
                }

                history.push(tool_result_message(&tool_result));
                if let Some(reminder) = progress.take_recovery_reminder() {
                    history.push(ChatMessage::System(reminder));
                }
                let _ = events.send(AgentEvent::ToolFinished(tool_result)).await;

                if same_call_repeat_count >= 3 {
                    let _ = events
                        .send(AgentEvent::Warning(AgentWarning::LoopDetected(
                            call.name.as_str().to_string(),
                        )))
                        .await;
                    budget_exhausted = Some(AgentLimit::RepeatedToolCall);
                    break 'drive;
                }
                if progress.has_no_progress() {
                    let _ = events
                        .send(AgentEvent::Warning(AgentWarning::NoProgress))
                        .await;
                    budget_exhausted = Some(AgentLimit::NoProgress);
                    break 'drive;
                }
                if consecutive_failures >= self.limits.max_consecutive_failures {
                    budget_exhausted = Some(AgentLimit::ConsecutiveFailures);
                    break 'drive;
                }
            }
        }

        let (final_text, termination) = if let Some(limit) = budget_exhausted {
            let summary = self
                .soft_land(
                    &request,
                    &mut history,
                    limit,
                    &changed_files,
                    &recent_tool_log,
                    &mut stats,
                    events,
                    &cancellation,
                )
                .await?;
            (summary, TerminationReason::BudgetExhausted(limit))
        } else {
            (
                normal_final_text.unwrap_or_default(),
                TerminationReason::Normal,
            )
        };

        Ok(AgentCompletion {
            run_id,
            final_text,
            stats,
            history,
            termination,
        })
    }

    /// Wraps up a run that hit a safety limit with one final no-tools inference asking the
    /// model to summarize its progress, so the run ends with an honest partial result instead
    /// of stopping silently mid-work. Falls back to a locally assembled summary if that
    /// inference itself fails.
    #[allow(
        clippy::too_many_arguments,
        reason = "internal helper, not part of the public API"
    )]
    async fn soft_land(
        &self,
        request: &AgentRequest,
        history: &mut Vec<ChatMessage>,
        limit: AgentLimit,
        changed_files: &BTreeSet<PathBuf>,
        recent_tool_log: &VecDeque<String>,
        stats: &mut AgentRunStats,
        events: &mpsc::Sender<AgentEvent>,
        cancellation: &CancellationToken,
    ) -> Result<String, AgentError> {
        let _ = events
            .send(AgentEvent::Warning(AgentWarning::BudgetExhausted(limit)))
            .await;

        if cancellation.is_cancelled() {
            return Err(AgentError::Cancelled);
        }

        let prompt = match limit {
            AgentLimit::ValidationPending => VALIDATION_PENDING_PROMPT,
            _ => SOFT_LANDING_PROMPT,
        };
        history.push(ChatMessage::User(prompt.into()));
        let _ = events
            .send(AgentEvent::StateChanged(AgentState::Inference))
            .await;

        let summary = match self
            .run_turn(request, history, &[], events, cancellation)
            .await
        {
            Ok((text, _tool_calls, input_tokens)) => {
                stats.turns += 1;
                if input_tokens.is_some() {
                    stats.last_input_tokens = input_tokens;
                }
                text.unwrap_or_else(|| local_budget_summary(limit, changed_files, recent_tool_log))
            }
            Err(AgentError::Cancelled) => return Err(AgentError::Cancelled),
            Err(_) => local_budget_summary(limit, changed_files, recent_tool_log),
        };

        history.push(ChatMessage::Assistant {
            text: Some(summary.clone()),
            tool_calls: Vec::new(),
        });

        Ok(summary)
    }

    async fn run_turn(
        &self,
        request: &AgentRequest,
        history: &[ChatMessage],
        tool_defs: &[gocode_core::ToolDefinition],
        events: &mpsc::Sender<AgentEvent>,
        cancellation: &CancellationToken,
    ) -> Result<(Option<String>, Vec<ToolCall>, Option<u64>), AgentError> {
        let chat_request = build_request(
            RequestContext {
                model: request.model.clone(),
                project_overview: request.project_overview.as_deref(),
                project_instructions: request.instructions.as_deref(),
                skills_summary: request.skills_summary.as_deref(),
                reasoning_effort: request.reasoning_effort.clone(),
                personality: request.personality,
            },
            history,
            tool_defs.to_vec(),
        );

        let mut stream = self
            .provider
            .stream_chat(chat_request, cancellation.clone())
            .await
            .map_err(AgentError::Provider)?;

        let mut text = String::new();
        let mut assembler = ToolCallAssembler::default();
        let mut input_tokens = None;
        let mut finish_reason = None;

        loop {
            tokio::select! {
                () = cancellation.cancelled() => return Err(AgentError::Cancelled),
                event = stream.recv() => match event {
                    Some(Ok(ChatStreamEvent::TextDelta(delta))) => {
                        if text.chars().count().saturating_add(delta.chars().count())
                            > self.limits.max_response_chars
                        {
                            return Err(AgentError::LimitReached(AgentLimit::ResponseTooLarge));
                        }
                        text.push_str(&delta);
                        let _ = events.send(AgentEvent::TextDelta(delta)).await;
                    }
                    Some(Ok(ChatStreamEvent::ReasoningDelta(delta))) => {
                        // Not accumulated into `text`: reasoning is shown to the user but never
                        // sent back as conversation history.
                        let _ = events.send(AgentEvent::ReasoningDelta(delta)).await;
                    }
                    Some(Ok(ChatStreamEvent::ToolCallDelta(delta))) => {
                        if !assembler.apply(delta) {
                            return Err(AgentError::LimitReached(AgentLimit::ToolCallPayloadTooLarge));
                        }
                    }
                    Some(Ok(ChatStreamEvent::Finished(FinishReason::Cancelled))) => {
                        return Err(AgentError::Cancelled);
                    }
                    Some(Ok(ChatStreamEvent::Usage(usage))) => {
                        input_tokens = usage.input_tokens;
                    }
                    Some(Ok(ChatStreamEvent::Finished(reason))) => {
                        finish_reason = Some(reason);
                    }
                    Some(Ok(ChatStreamEvent::RequestId(_))) => {}
                    Some(Err(error)) => return Err(AgentError::Provider(error)),
                    None => break,
                },
            }
        }

        let tool_calls = assembler.finish();
        if matches!(finish_reason, Some(FinishReason::Length))
            && text.is_empty()
            && tool_calls.is_empty()
        {
            let _ = events
                .send(AgentEvent::Warning(AgentWarning::TruncatedBeforeContent))
                .await;
        }

        let text = (!text.is_empty()).then_some(text);
        Ok((text, tool_calls, input_tokens))
    }

    async fn execute_tool(
        &self,
        request: &AgentRequest,
        call: &ToolCall,
        tool_cancellation: &tokio_util::sync::CancellationToken,
        events: &mpsc::Sender<AgentEvent>,
    ) -> Result<ToolResult, AgentError> {
        let Some(tool) = self.tools.get(&call.name) else {
            let _ = events
                .send(AgentEvent::Warning(AgentWarning::UnknownTool(
                    call.name.as_str().to_string(),
                )))
                .await;
            return Ok(ToolResult::failed(
                call.id.clone(),
                format!("Tool \"{}\" is not available.", call.name),
            ));
        };

        let _ = events.send(AgentEvent::ToolStarted(call.id.clone())).await;

        let sink: Arc<dyn ToolEventSink> = Arc::new(AgentToolEventSink {
            events: events.clone(),
        });
        let ctx = ToolContext::new(
            call.id.clone(),
            request.project_root.clone(),
            self.permissions.clone(),
        )
        .with_cancellation(tool_cancellation.clone())
        .with_events(sink);

        match tool.execute(ctx, call.arguments.clone()).await {
            Ok(result) => Ok(result),
            Err(ToolError::Cancelled) => Err(AgentError::Cancelled),
            Err(error) => Ok(ToolResult::failed(call.id.clone(), error.to_string())),
        }
    }
}

/// Cancels `tool_cancellation` when `core_cancellation` fires, and stops watching once dropped.
fn bridge_cancellation(
    core_cancellation: CancellationToken,
    tool_cancellation: tokio_util::sync::CancellationToken,
) -> BridgeGuard {
    let (done_tx, done_rx) = tokio::sync::oneshot::channel::<()>();
    tokio::spawn(async move {
        tokio::select! {
            () = core_cancellation.cancelled() => tool_cancellation.cancel(),
            _ = done_rx => {}
        }
    });
    BridgeGuard(Some(done_tx))
}

struct BridgeGuard(Option<tokio::sync::oneshot::Sender<()>>);

impl Drop for BridgeGuard {
    fn drop(&mut self) {
        if let Some(sender) = self.0.take() {
            let _ = sender.send(());
        }
    }
}

struct AgentToolEventSink {
    events: mpsc::Sender<AgentEvent>,
}

impl ToolEventSink for AgentToolEventSink {
    fn emit(&self, event: ToolEvent) {
        if let ToolEvent::OutputChunk { id, chunk } = event {
            // Sent synchronously (not spawned) so it lands on the channel in the same order it
            // was emitted relative to the run's other events, notably `AgentEvent::Completed`.
            let _ = self
                .events
                .try_send(AgentEvent::ToolOutputChunk { id, chunk });
        }
    }
}

/// For a `write_file` or `apply_patch` call, reads every file it is about to touch so the run
/// can later report an undo snapshot; any other tool contributes nothing. Resolution or read
/// failures are treated the same as "file does not exist yet" — the write tool will surface its
/// own error if the path is genuinely invalid.
fn capture_before_snapshots(
    project_root: &Path,
    call: &ToolCall,
) -> HashMap<PathBuf, Option<String>> {
    let candidate_paths: Vec<String> = match call.name.as_str() {
        "write_file" => call
            .arguments
            .get("path")
            .and_then(serde_json::Value::as_str)
            .map(|path| vec![path.to_string()])
            .unwrap_or_default(),
        "apply_patch" => call
            .arguments
            .get("patch")
            .and_then(serde_json::Value::as_str)
            .map(gocode_tools::patch::touched_paths)
            .unwrap_or_default(),
        _ => Vec::new(),
    };

    candidate_paths
        .into_iter()
        .map(|path| {
            let before = read_workspace_file(project_root, Path::new(&path));
            (PathBuf::from(path), before)
        })
        .collect()
}

/// Reads a workspace-relative path's current content, or `None` if it does not exist or is not
/// readable as UTF-8 text.
fn read_workspace_file(project_root: &Path, relative: &Path) -> Option<String> {
    let resolved =
        gocode_tools::workspace::resolve_workspace_path(project_root, &relative.to_string_lossy())
            .ok()?;
    std::fs::read_to_string(resolved).ok()
}

fn map_tool_definitions(tools: &ToolRegistry) -> Vec<gocode_core::ToolDefinition> {
    tools
        .definitions()
        .into_iter()
        .map(|definition| gocode_core::ToolDefinition {
            name: definition.name.as_str().to_string(),
            description: definition.description,
            input_schema: definition.input_schema,
        })
        .collect()
}

fn to_provider_tool_call(call: &ToolCall) -> ProviderToolCall {
    ProviderToolCall {
        id: call.id.as_str().to_string(),
        name: call.name.as_str().to_string(),
        arguments: call.arguments.clone(),
    }
}

fn tool_evidence_signature(result: &ToolResult) -> String {
    format!(
        "{:?}\u{0}{:?}\u{0}{}\u{0}{}\u{0}{}",
        result.status,
        result.metadata.exit_code,
        result.metadata.truncated,
        result.output.truncated,
        result.output.content,
    )
}

fn tool_result_message(result: &ToolResult) -> ChatMessage {
    ChatMessage::Tool {
        tool_call_id: result.call_id.as_str().to_string(),
        content: result.output.content.clone(),
    }
}
